_pages/profile/[id]/submit-profile-form.js
Hi, I'm Ted — new to the community.
Problem: sometimes people upload videos that aren't the right size, which can cause them to lose ~$800:
Solution: check video dimensions on the client side prior to allowing submission of the form.
There's wide browser support for the api used: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadedmetadata_event#browser_compatibility
Let me know if this looks generally good, and if so I'll do some more exhaustive testing.
Note: If [HIP-8](https://snapshot.org/#/poh.eth/proposal/QmTZw1SnrQ7PTvvP6nf6tnNPFdKTKBJSnhEHZBzMBGqeeD) passes (it looks like it will), we'll want to change `minWidth` and `minHeight` from `360` to `352`.
Note: force-pushed in order to update the commit message to mach your conventions
=> feat: validate video dimensions in profile submit form

subgraph/src/mapping.ts
=> fix: detect if executeRequest reverted

tokenlog.json
And re enable quadratic voting. Now each person has 99 votes to spend quadratically.
=> chore(tokenlog): change contract address to BalanceScaler

.env.example, components/web3-provider.js, pages/_app.js
=> fix: check chainId when connected to provider to grant network compability

tokenlog.json
The new contract has all view functions an erc20.
=> chore(tokenlog): update contract address

_pages/index/submission-filters.js
1. Search for "Federico"
2. Erase seach input
3. Check browser history
This was fixed by replacing _router.push_ with _router.replace_.
=> Browser history being spammed

_pages/profile/[id]/submit-profile-form.js, components/form.stories.mdx
=> HIP-8: Accept 352 pixels as minimum dimension in video submissions

_pages/index/index.js, _pages/index/submission-filters.js, data/index.js, data/parsing.js, subgraph/schema.graphql, subgraph/src/mapping.ts
=> Feat: Stop displaying "Removed" profiles in the list of profiles

_pages/profile/[id]/submission-details-card/index.js, _pages/profile/[id]/submission-details-card/small-avatar.js
=> Feat: show sybil account on duplicate dispute

_pages/index/index.js, _pages/profile/[id]/index.js, _pages/profile/[id]/submit-profile-card.js, _pages/profile/[id]/submit-profile-form.js
=> Feat: Improve submit profile UX

_pages/profile/[id]/submit-profile-form.js
=> Fix: add *.avi and *.mov to supported video files

subgraph/src/mapping.ts
=> Fix: Voucher of duplicate appearing registered

_pages/profile/[id]/submission-details-card/index.js
=> Fix: fund button not appearing

_pages/profile/[id]/submission-details-accordion.js, _pages/profile/[id]/submission-details-card/index.js, components/voting-history.js, subgraph/src/mapping.ts
=> Fix: Appeal accordion not appearing

components/appeal.js
The appeal periods were correctly handled, even with tied results. I decided to disable the fund button and to add a label, so that the winner side can't fund the appeal in case the loser appeal period is finished and the appeal was not funded, to make it less confusing. Nonetheless, only one case is on appeal period right now, so I leave the proposal as a draft until it can be tested better.
=> Fix: hide appeal button if opposing party failed to fund

_pages/profile/[id]/submission-details-card/index.js
=> Fix: dont show save deposit info card when the profile is in pending status

package.json, pages/_app.js
Reverts Proof-Of-Humanity/proof-of-humanity-web#467
=> Revert "Fix: temporarily use the hosted service"

.eslintrc.js, _pages/index/index.js, _pages/profile/[id]/index.js
Added <title> tags to index and profile/[id] pages, any changes / ideas are welcome
=> feat(pages): Add page titles to site

package.json, pages/_app.js
Temporarily use the hosted service for the subgraph by reverting Proof-Of-Humanity/proof-of-humanity-web#475
=> Fix: temporarily use the hosted service by reverting #475

_pages/profile/[id]/submission-details-card/index.js, package-lock.json, package.json
Vouchees are now shown ordered in a descending manner based on the lastStatusChange param from the submission.
=> feat(vouchees): ordered by lastStatusChange

subgraph/src/mapping.ts
Set submission disputed to false if the latest request for the submission has no more parallel disputes.
=> Fix: Disputed to false

package.json, pages/_app.js
Reverts Proof-Of-Humanity/proof-of-humanity-web#493
=> Revert "Fix: temporarily use the hosted service #475"

_pages/profile/[id]/submit-profile-form.js
=> Fix: Prevent triggering a transaction twice when submitting and scroll to the bottom instead of the top.

_pages/index/index.js, _pages/index/submission-card.js, _pages/profile/[id]/index.js, _pages/profile/[id]/submission-details-card/deadlines/index.js, _pages/profile/[id]/submit-profile-card.js
Will replace fetching from the graph with fetching from the contract for some of the wrong values pulled by the graph (arbitratorExtraData and submissionDuration)
=> fix:temporary fix for the graph issue

components/web3-provider.js, package.json, subgraph/config/goerli.json, subgraph/config/index.js, subgraph/config/kovan.json
changed the tx batcher address to a real one deployed in goerli and removed support for Kovan
=> Goerli support

.env.example, CONTRIBUTING.md, _pages/profile/[id]/submission-details-card/deadlines/remove-button.js, _pages/profile/[id]/submit-profile-form.js, components/archon-provider.js, components/escrow-widget.js, components/kleros-escrow.js, components/kleros-escrow.stories.mdx, components/submit-evidence-button.js, netlify.toml, scripts/utils.js
- updates uploads to use Court-Function's upload-to-ipfs functions
- env variable required `NEXT_PUBLIC_COURT_FUNCTIONS_URL`
=> chore: use-court-functions-upload-to-ipfs-function
