Proof-Of-Humanity/proof-of-humanity-web

- README.md
- _pages/profile/[id]/submit-profile-card.js
This:
- Lowers the limit accepted by the video uploader to avoid exceeding the browser's quota
- Disallows avi and mov due to poor browser playback support.
> fix: remove support for avi and mov videos and decrease limit size

- _pages/profile/[id]/submission-details-card/ubi-card.js
functionally, it displays real time wallet balance, so instead of saying ubi accrued, we should only just ubi, to be consistent
> refactor(ubi-card): change UBI Accrued to UBI

- CHANGELOG.md
- components/popup.js
`<Popup modal>` won't allow scroll content on small screens
Fix is to allow scroll on overlay, example:
https://user-images.githubusercontent.com/1024246/113912210-da6fec00-97a8-11eb-9202-ff9fa11d8160.mp4
Allow people to use a browser mobile wallet to interact with the dapp.
Run storybook and change "Content" to a long content in popup stories.
> fix: let popup modal scroll when content is long

- pages/_app.js
Resolves #133 
Removes adding `?network=mainnet` query to the URL by default. If user explicitly visits `?network=kovan` but web3 is connected to `mainnet`, the URL will be changed to `?network=mainnet` to reflect the change. Let me know if you think, we should just remove the query in this case as well
> fix: remove default network from query params

- _pages/profile/[id]/submission-details-card/ubi-card.js
The button as it is right now incorrectly prevents users from finalizing their applications. Removing this until a proper fix is found.
> fix: don't prevent users from submitting the tx

- _pages/profile/[id]/submit-profile-form.js
A simple fix for #308
Adds disabled state to submit button using Formik's `isSubmitting`
This isn't the most elegant solution, but quickly addresses the issue with minimal regression risk. We still don't handle the users experience once the transaction is confirmed (and web3 returns the hash). Ideally this would be a dialog or landing page. I will put in a separate issue for this.
> fix: block multiple request submissions #308

- package-lock.json
This fixes the build issue that new people run into when cloning the project for dev purposes. For discussion, see https://github.com/Proof-Of-Humanity/proof-of-humanity-web/pull/309
The changelog is solely the result of running `npm update keccak256` on an empty clone of the project that has no `node_modules/` folder. The important bit is the update to the keccak/keccak256 versions, but as a side effect it seems that `npm update` removed a bunch of cruft from `package-lock.json`.
Note: it seems that `package-lock.json` has generally drifted some from `package.json`; if you remove `package-lock.json` and try to `npm install`, you run into incompat dependency issues. We'll want to fix that at some point, but it seems like a separate issue.
> fix: update keccak to make project compatible with versions of node >10

- subgraph/schema.graphql
- subgraph/src/mapping.ts
Previous code was saving the disputeID in the `ruling` field of the challenge.
Also added additional fields to allow more flexible and efficient queries.
> Fix: incorrect ruling value

- _pages/index/submission-filters.js
1. Filter by "Registered" 
2. Filter by "ALL"
3. Cards are still filtered by "Registered"
This was fixed by including the _pathname: '/'_ key/value to the object that _router.push_ receives.
> ALL option not working in SELECT INPUT

- _pages/index/submission-filters.js
1. Search for "Federico"
2. The profile "Federico Ast" appears
3. Search for "Federico Ast"
4. No profiles appear
This was fixed by removing a line that replaced spaces with &.
> Using spaces doesn't work in search bar

- _pages/index/submission-filters.js
1. Search for "Tom"
2. Try to delete search input
3. "T" can't be erased
This was fixed by adding the _pathname: '/'_ key/value to the object passed to _router.push_.
> Frozen letter in search bar

- _pages/index/submission-filters.js
1. Go to search bar
2. Space a few times
3. Input is filled by "&"
This bug comes from a line that was kept in a prior merge, .replaceAll() was removed to fix it.
> When spacing, search input is filled by &

- _pages/profile/[id]/submission-details-card/ubi-card.js
Before this PR, if a user was not registered but had UBI (say for example, because they bought it), the UI would display the balance increasing.
> fix: don't accrue on unregistered profiles

- _pages/profile/[id]/submission-details-card/deadlines/challenge-button.js
The error arose when trying to submit a challenge with no justification. We have decided to make the justification mandatory in the UI, so the button will be disabled unless there is something written on the field.
> Fix: Can't challenge using duplicate as a reason

- _pages/index/app-query.js
- components/account-settings-popup.js
An id (presumably) used to uniquely identify Challenge in thegraph `challenge.id` was confused with the contract's way to identify challenges, `challenge.challengeID` , the latter is what had to be fed into batchSend.
I messed up the [first PR](https://github.com/Proof-Of-Humanity/proof-of-humanity-web/pull/423), sorry.
> fix: batchSend now sends correct challengeID

- _pages/profile/[id]/submission-details-card/deadlines/remove-button.js
It was only taking 2 bytes files at maximum.
Now it takes up to 2 MB.
> fix: upload file to remove request modal

- subgraph/schema.graphql
- subgraph/src/mapping.ts
Solves #462.
In this case, the user re-submitted his profile immediately after being rejected and the bot couldn't be aware of it https://github.com/kleros/action-callback-bots/blob/master/src/bots/proof-of-humanity/process-vouches.js.
> fix: vouchReleaseReady per request instead of per submission

- _pages/profile/[id]/submission-details-accordion.js
- components/evidence.js
I added an Alert on the Evidence component to let disputed people know that sending evidence might not help with the dispute if their submission is, indeed, incorrect. 
Should be simple to merge into the master of the repo.
> feat(evidence): added advice on evidence component

- subgraph/src/mapping.ts
This may not be correct.
What happens if someone reapplies while there's an ongoing
dispute? Would that cause a bug in the future?
> fix(subgraph): disputed to false reapplySubmission

- CONTRIBUTING.md
Workaround for webpack error: `ERR_OSSL_EVP_UNSUPPORTED`
> docs: add workaround for SSL error

- _pages/profile/[id]/submission-details-card/small-avatar.js
- components/theme-provider.js
As we discussed on #483, one of the possible measures is to somehow "flag" profiles that are maliciously vouching.
On that branch I had pushed a change to show red small avatars for the vouchees that had been disputed and removed. Given that #483 is under heavy discussion, I decided to separate those two features onto two different PRs and branches. 
I believe this change should be included in master right away.
> feat(smallAvatar): display on red disputed and removed vouchees

- .gitignore
- _pages/profile/[id]/submission-details-card/deadlines/remove-button.js
removal requests from a different wallet need to have a video attached as evidence to prove ownership of the registrated address. 
UI didn't allow video files to be attached. it is corrected now.
> fix: corrected removal request evidence file types
